name: Docker CI/CD

on:
  push:
    branches:
      - main  # or your branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Check Docker login
      - name: Verify Docker login
        run: docker info

      # Step 4: Pull Docker image
      - name: Pull Docker image
        run: docker pull chiranjeevi001/wisecow:latest

      # Step 5: (Optional) Push Docker image after tagging
      - name: Tag and Push Docker image
        run: |
          docker tag chiranjeevi001/wisecow:latest ${DOCKER_USERNAME}/wisecow:latest
          docker push ${DOCKER_USERNAME}/wisecow:latest

